/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.112
 * Generated at: 2026-03-20 06:18:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class form_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1770863239401L));
    _jspx_dependants.put("jar:file:/C:/javaPro/1.Movie/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/movie/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<!-- jquery cnd -->\r\n");
      out.write(" <script src=\"https://code.jquery.com/jquery-2.2.4.min.js\" integrity=\"sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>회원가입</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container py-5\">\r\n");
      out.write("    <div class=\"row justify-content-center\">\r\n");
      out.write("        <div class=\"col-md-6\">\r\n");
      out.write("            <div class=\"card shadow p-4\"> <div class=\"text-center mb-3\">\r\n");
      out.write("                    <span class=\"logo\">MOVIE</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <h4 class=\"text-center mb-4\">회원가입</h4>\r\n");
      out.write("                \r\n");
      out.write("                ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                \r\n");
      out.write("                <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/join\" method=\"post\"> <div class=\"mb-3\">\r\n");
      out.write("                    <label class=\"form-label\">아이디 *</label>\r\n");
      out.write("                    <div class=\"input-group\">\r\n");
      out.write("                        <input type=\"text\" name=\"uid\" id=\"uid\" class=\"form-control\" maxlength=\"15\" required>\r\n");
      out.write("                        <button type=\"button\" class=\"btn btn-outline-gray\" onclick=\"IdCheck()\">중복확인</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <small id=\"idMsg\"></small>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"mb-3\">\r\n");
      out.write("                    <label class=\"form-label\">비밀번호 *</label>\r\n");
      out.write("                    <input type=\"password\" name=\"upw\" id=\"upw\" class=\"form-control\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"mb-3\">\r\n");
      out.write("                    <label class=\"form-label\">비밀번호 확인 *</label>\r\n");
      out.write("                    <input type=\"password\" id=\"upwConfirm\" class=\"form-control\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"mb-3\">\r\n");
      out.write("                    <label class=\"form-label\">이름 *</label>\r\n");
      out.write("                    <input type=\"text\" name=\"uname\" class=\"form-control\" maxlength=\"15\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"mb-4\">\r\n");
      out.write("                    <label class=\"form-label\">주소</label>\r\n");
      out.write("                    <input type=\"text\" name=\"uaddr\" id=\"uaddr\" class=\"form-control\" onclick=\"searchAddr()\" readonly> </div>\r\n");
      out.write("                <div class=\"mb-3\">\r\n");
      out.write("                    <label class=\"form-label\">이메일 *</label>\r\n");
      out.write("                    <div class=\"input-group\">\r\n");
      out.write("                        <input type=\"email\" name=\"umail\" id=\"umail\" class=\"form-control\" maxlength=\"50\" required>\r\n");
      out.write("                        <button type=\"button\" class=\"btn btn-outline-gray\" onclick=\"mailCheck()\">중복확인</button> </div>\r\n");
      out.write("                    <small id=\"mailMsg\"></small>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"mb-3\">\r\n");
      out.write("                    <label class=\"form-label\">전화번호 *</label>\r\n");
      out.write("                    <input type=\"text\" name=\"uphone\" class=\"form-control\" maxlength=\"13\" placeholder=\"010-0000-0000\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"mb-3\">\r\n");
      out.write("                    <label class=\"form-label\">생년월일 *</label>\r\n");
      out.write("                    <input type=\"date\" name=\"ubirth\" class=\"form-control\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"mb-3\">\r\n");
      out.write("                    <label class=\"form-label\">성별</label>\r\n");
      out.write("                    <div class=\"form-check form-check-inline\">\r\n");
      out.write("                        <input type=\"radio\" name=\"ugender\" value=\"M\" class=\"form-check-input\" id=\"male\" checked>\r\n");
      out.write("                        <label class=\"form-check-label\" for=\"male\">남성</label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-check form-check-inline\">\r\n");
      out.write("                        <input type=\"radio\" name=\"ugender\" value=\"F\" class=\"form-check-input\" id=\"female\">\r\n");
      out.write("                        <label class=\"form-check-label\" for=\"female\">여성</label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"d-grid\">\r\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-netflix\" onclick=\"return validateForm()\">가입하기</button>\r\n");
      out.write("                </div>\r\n");
      out.write("                </form> \r\n");
      out.write("                <hr style=\"border-color: #333;\" class=\"mt-4\">\r\n");
      out.write("                <p class=\"text-center mb-0\" style=\"color: #aaa;\">\r\n");
      out.write("                	이미 회원이신가요? <a href=\"/user/logForm\">로그인</a>\r\n");
      out.write("                </p>\r\n");
      out.write("			</div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function IdCheck() {\r\n");
      out.write("	var uid = document.getElementById('uid').value.trim();\r\n");
      out.write("	if(!uid){alert('아이디를 입력하세요.'); return;}\r\n");
      out.write("	fetch('/user/IdCheck?uid=' + encodeURIComponent(uid))\r\n");
      out.write("		.then(function(r) {return r.text();})\r\n");
      out.write("		.then(function(data) {\r\n");
      out.write("			var el = document.getElementById('idMsg');\r\n");
      out.write("			if(data === 'available'){\r\n");
      out.write("				el.style.color = '#5cb85c';\r\n");
      out.write("				el.innerText = '사용 가능한 아이디입니다.';\r\n");
      out.write("			}else{\r\n");
      out.write("				el.style.color = '#E50914';\r\n");
      out.write("				el.innerText = '이미 사용 중인 아이디입니다.';\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("function mailCheck() {\r\n");
      out.write("	var umail = document.getElementById('umail').value.trim();\r\n");
      out.write("	if(!umail) {alert('이메일을 입력하세요.'); return;}\r\n");
      out.write("	fetch('/user/mailCheck?umail=' + encodeURIComponent(umail))\r\n");
      out.write("		.then(function(r) {return r.text();})\r\n");
      out.write("		.then(function (data) {\r\n");
      out.write("			var el = document.getElementById('mailMsg');\r\n");
      out.write("			if(data === 'available'){\r\n");
      out.write("				el.style.color = '#5cb85c';\r\n");
      out.write("				el.innerText = '사용 가능한 이메일입니다.';\r\n");
      out.write("			}else{\r\n");
      out.write("				el.style.color = '#E50914';\r\n");
      out.write("				el.innerText = '이미 등록된 이메일입니다.';\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function validateForm() {\r\n");
      out.write("	var upw = document.getElementById('upw').value;\r\n");
      out.write("	var confirm = document.getElementById('upwConfirm').value;\r\n");
      out.write("	if(upw !== confirm){\r\n");
      out.write("		alert('비밀번호가 일치하지 않습니다.');\r\n");
      out.write("		return false;\r\n");
      out.write("	}\r\n");
      out.write("	return true;\r\n");
      out.write("}\r\n");
      out.write("function searchAddr() {\r\n");
      out.write("	new daum.Postcode({\r\n");
      out.write("		oncomplete : function(data) {\r\n");
      out.write("			var addr = data.roadAddress;\r\n");
      out.write("			document.getElementById(\"uaddr\").value = addr;\r\n");
      out.write("		}\r\n");
      out.write("	}).open();\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /WEB-INF/views/user/form.jsp(23,16) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty msg}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("                    <div class=\"alert alert-danger\">");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("</div>\r\n");
        out.write("                ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }
}
